spring.application.name=BootMSProj08-CustomerServiceMS-VSMS-Consumer

#MS port number
server.port=7072

#register with Eureka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka

# make  this  MS (Config Client) connecting to Config Server  
spring.config.import=optional:configserver:

#Activate the actuators
#management.endpoints.web.exposure.include=*